### ISSUE TITLE
what happens to razee deployment when kubernetes version is changed?

### ISSUE THREAD

**Issue by asm582** [razee-io/razeedeploy-delta#88]
I have heard that razee uses Kubernetes to manage Kubernetes, curious to know what happens to razee deployed components when Kubernetes version is updated in all the clusters?

**Comment by alewitt2** [comment]
im not sure i fully understand your question, but i will try to explain what we do and hopefully that clears things up..

The components we create are just more Deployments that run on top of Kubernetes itself. And we aren't managing Kubernetes, we manage Kubernetes resources. So, essentially whats going on is our code runs as a Kubernetes Deployment, and we talk to the Kubernetes API server directly, in order to add, modify, and delete Kubernetes resources (eg. configmaps, deployments, etc.). 

So in with this context, to answer your question directly, when Kubernetes updates, nothing drastically changes for razee, because we are only run on top of kubernetes making requests to the underlying api server.

**Comment by asm582** [comment]
Thanks!
